devs   = ["Anusha", "Danny", "Fraser", "Paul", "Richy", "Ryan", "Sean", "Zak", "Muhammed"]
design = ["Freshta", "Jacob", "Jess", "Matt", "Shail", "Victoria"]
admin  = ["Alok", "Maria", "Yomi"]

team_name = "Neighbourhood Watch"
