devs   = ["Anusha", "Danny", "Fraser", "Paul", "Richy", "Ryan", "Sean", "Zak", "Muhammed"]
design = ["Jacob", "Matt", "Shail", "Victoria"]
admin  = ["Alok", "Maria"]

team_name = "Neighbourhood Watch"
