devs   = ["Anusha", "Danny", "Fraser", "Paul", "Richy", "Sean", "Zak", "Muhammed"]
design = ["Freshta", "Jacob", "Jess", "Matt", "Shail"]
admin  = ["Alok", "Morgan", "Maria", "Yomi"]

team_name = "Neighbourhood Watch"
