devs   = ["Dan", "Danny", "Don", "Ewan", "Olufemi", "Richy", "Sarthak", "Sean", "Zak", "Abdi"]
design = ["Helen", "Jacob", "Sam", "Shail"]
admin  = ["Alok", "Maria"]

team_name = "Neighbourhood Watch"