devs   = ["James", "John", "Manpreet", "Kannan", "Kuldeep", "Yang", "Blaine"]
design = ["Alex", "Jacob", "Matt", "Shail", "Steven", "Stuart", "Victoria"]
admin  = ["Alok", "Maria"]

team_name = "Team Alpha"
