devs   = ["James", "John", "Manpreet", "Kannan", "Kuldeep", "Ryan", "Yang", "William"]
design = ["Freshta", "Jacob", "Jess", "Matt", "Shail", "Victoria"]
admin  = ["Alok", "Maria", "Yomi"]

team_name = "Team Alpha"
